name: Publish static website
on:
  workflow_call:
    inputs:
      workload-identity-provider:
        description: Full identifier of the GitHub workload identity pool provider in Google Cloud
        type: string
        required: true
      uploader-service-account:
        description: Email of the Google Cloud service account for uploading the website files
        type: string
        required: true
      target-bucket:
        description: The gsutil target bucket path to upload the static files to
        type: string
        required: true
      website-service-url-map:
        description: The website service URL map name to use for CDN cache invalidation
        type: string
        required: true
      https-redirect-url-map:
        description: The HTTP to HTTPS redirection URL map name to use for CDN cache invalidation
        type: string
        required: true
      python-version:
        description: The Python version to use
        type: number
        required: false
        default: 3.8
      requirements:
        description: The requirements file to use for generating the static files.
        type: string
        required: false
        default: requirements/dev.txt

concurrency: ${{ github.workflow }}-publish-${{ github.ref }}

jobs:
  website:
    name: Publish website
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ inputs.workload-identity-provider }}
          service_account: ${{ inputs.uploader-service-account }}
      - uses: google-github-actions/setup-gcloud@v1

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - uses: logikal-io/make-orb@v1
        with:
          requirements: ${{ inputs.requirements }}

      - name: Sync database
        run: orb --command 'manage syncdb --no-input'

      - name: Generate static files
        run: orb --command 'manage generate --no-input'

      - name: Upload files
        shell: bash
        run: gsutil -m rsync -r -d -j html,css,js generated "gs://${{ inputs.target-bucket }}/"

      - name: Invalidate CDN cache
        run: |-
          gcloud compute url-maps invalidate-cdn-cache \
            "${{ inputs.website-service-url-map }}" --path "/*"
          gcloud compute url-maps invalidate-cdn-cache \
            "${{ inputs.https-redirect-url-map }}" --path "/*"
