name: Publish release
on:
  workflow_call:
    inputs:
      name:
        description: The name of the package to publish
        type: string
        required: true
      python-version:
        description: The Python version to use
        type: number
        required: false
        default: 3.8
      docs-requirements:
        description: The path to the requirements file to use for documentation building
        type: string
        required: false
        default: requirements/docs.txt
      build-requirements:
        description: The path to the requirements file to use for package building
        type: string
        required: false
        default: requirements/build.txt
      hadoop-version:
        description: The Hadoop version to install
        type: string
        required: false
      hadoop-gcs-connector-version:
        description: The Hadoop Google Cloud Storage connector version to install
        type: string
        required: false
      hadoop-aws-module-version:
        description: The Hadoop AWS module version to install
        type: string
        required: false
      aws-java-sdk-version:
        description: The AWS Java SDK bundle version that was used to compile the Hadoop AWS module
        type: string
        required: false

    secrets:
      DOCS_WORKLOAD_IDENTITY_PROVIDER:
        description: Full identifier of the GitHub workload identity pool provider in Google Cloud
        required: true
      DOCS_UPLOADER_SERVICE_ACCOUNT:
        description: Email of the Google Cloud service account for uploading documentation files
        required: true
      DOCS_TARGET_BUCKET:
        description: The gsutil target bucket path to upload the documentation to
        required: true
      DOCS_WEBSITE_SERVICE_URL_MAP:
        description: The website service URL map name to use for CDN cache invalidation
        required: true
      DOCS_HTTPS_REDIRECT_URL_MAP:
        description: The HTTP to HTTPS redirection URL map name to use for CDN cache invalidation
        required: true

jobs:
  documentation:
    name: Publish documentation
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.DOCS_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.DOCS_UPLOADER_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - uses: logikal-io/make-orb@v1
        with:
          requirements: ${{ inputs.docs-requirements }}

      - uses: logikal-io/install-hadoop@v1
        if: inputs.hadoop-version != ''
        with:
          version: ${{ inputs.hadoop-version }}
          gcs-connector-version: ${{ inputs.hadoop-gcs-connector-version }}
          aws-module-version: ${{ inputs.hadoop-aws-module-version }}
          aws-java-sdk-version: ${{ inputs.aws-java-sdk-version }}

      - name: Get latest tag
        id: tags
        run: echo "latest=$(git tag -l --sort=version:refname | tail -n 1)" >> $GITHUB_OUTPUT

      - name: Build documentation
        run: orb --command 'docs --build'

      - name: Upload documentation
        shell: bash
        env:
          tag: ${{ github.ref_name }}
        run: |-
          version="${tag:1}"
          if [[ ! ${version} ]]; then
            echo "Invalid tag"
            exit 1
          fi
          gsutil -m rsync -r -d -j html,css,js -x "\.buildinfo|\.doctrees" \
            docs/build "gs://${{ secrets.DOCS_TARGET_BUCKET }}/${{ inputs.name }}/${version}"

      - name: Upload latest documentation
        if: github.ref_name == steps.tags.outputs.latest
        run: >-
          gsutil -m rsync -r -d -j html,css,js -x "\.buildinfo|\.doctrees" \
            docs/build "gs://${{ secrets.DOCS_TARGET_BUCKET }}/${{ inputs.name }}/latest"

      - name: Invalidate CDN cache
        if: github.ref_name == steps.tags.outputs.latest
        run: |-
          gcloud compute url-maps invalidate-cdn-cache \
            "${{ secrets.DOCS_WEBSITE_SERVICE_URL_MAP }}" --path "/${{ inputs.name }}/latest/*"
          gcloud compute url-maps invalidate-cdn-cache \
            "${{ secrets.DOCS_HTTPS_REDIRECT_URL_MAP }}" --path "/${{ inputs.name }}/latest/*"

  package:
    name: Publish package
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - uses: logikal-io/make-orb@v1
        with:
          requirements: ${{ inputs.build-requirements }}

      - name: Build package
        run: orb --command 'python -m build --sdist --wheel'

      # Manual command: twine upload dist/*
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
