name: Push image
on:
  workflow_call:
    inputs:
      name:
        description: The name of the image
        type: string
        required: true
      dockerfile:
        description: The path to the relevant Dockerfile
        type: string
        required: false
        default: Dockerfile
      build-path:
        description: The build path to use
        type: string
        required: false
        default: .
      aws-role-to-assume:
        description: The AWS role to assume
        type: string
        required: true
      aws-region:
        description: The AWS region to use
        type: string
        required: true

jobs:
  push-image:
    name: Push image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        id: aws
        with:
          role-to-assume: ${{ inputs.aws-role-to-assume }}
          aws-region: ${{ inputs.aws-region }}

      - name: Build and push image
        env:
          name: ${{ inputs.name }}:latest
          registry: >-
            ${{ steps.aws.outputs.aws-account-id }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com
        run: |-
          aws ecr-public get-login-password --region us-east-1 | \
              docker login --username AWS --password-stdin public.ecr.aws
          aws ecr get-login-password --region "${{ inputs.aws-region }}" | \
              docker login --username AWS --password-stdin "${registry}"
          docker build --tag "${registry}/${name}" --file "${{ inputs.dockerfile }}" "${{ inputs.build-path }}"
          docker push "${registry}/${name}"
